@PORT=8000
@BASE_URL=http://localhost:{{PORT}}/api/v1


GET {{BASE_URL}}
### 
GET {{BASE_URL}}/users
###
POST  {{BASE_URL}}/users
###
GET {{BASE_URL}}/users/2
###
PATCH  {{BASE_URL}}/users/2
###
DELETE  {{BASE_URL}}/users/2

###
POST {{BASE_URL}}/auth/register

###
POST {{BASE_URL}}/auth/login

###
POST {{BASE_URL}}/posts
Content-Type: application/json

{
  "content": "test"
}
